services:

  sinapsis-time-series-forecasting-main: &default
    image: sinapsis-time-series-forecasting:base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      ssh:
        - default
    shm_size: '8gb'
    environment:
      PYTHONUNBUFFERED: 1
      GRADIO_SHARE_APP: ${GRADIO_SHARE_APP:-false}
      PYTHONPATH: /lib/python3.10/:/app/.venv/lib/python3.10/site-packages
    volumes:
      - "~/.cache/torch:/root/.cache/torch"
      - "../artifacts/:/root/.cache/sinapsis"
      - "~/.cache/sinapsis/:/root/.cache/sinapsis"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]